package usuarios.vistas;

import interfaces.IControladorUsuarios;
import javax.swing.JDialog;
import javax.swing.JTable;
import javax.swing.JTextField;
import principal.controladores.ModeloTablaUsuarios;
import principal.vistas.VentanaPrincipal;

public class VentanaUsuario extends JDialog {
    
    private ModeloTablaUsuarios mtu;
    private IControladorUsuarios icu;
    private VentanaPrincipal vp;
    
    public VentanaUsuario(IControladorUsuarios icu, java.awt.Frame ventanaPadre, boolean modal) {
        super(ventanaPadre, modal);
        initComponents();
        this.icu = icu;
        ModeloTablaUsuarios mtu = new ModeloTablaUsuarios();
    }
    
    public JTextField verApellido() {
        return this.txtApellidoPresionarTecla;
    }
    
    public JTable verTablaUsuarios() {
        return JTabla;
    }
    
    public ModeloTablaUsuarios verModelo() {
        return mtu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVolverClic = new javax.swing.JButton();
        ApellidoTitulo = new javax.swing.JLabel();
        txtApellidoPresionarTecla = new javax.swing.JTextField();
        BtnBuscarClic = new javax.swing.JButton();
        btnNuevoClic = new javax.swing.JButton();
        btnModificarClic = new javax.swing.JButton();
        btnBorrarClic = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        JTabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        btnVolverClic.setForeground(new java.awt.Color(51, 0, 153));
        btnVolverClic.setText("Volver");
        btnVolverClic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverClicActionPerformed(evt);
            }
        });

        ApellidoTitulo.setForeground(new java.awt.Color(0, 102, 102));
        ApellidoTitulo.setText("Apellido:");

        BtnBuscarClic.setForeground(new java.awt.Color(51, 0, 153));
        BtnBuscarClic.setText("Buscar");
        BtnBuscarClic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarClicActionPerformed(evt);
            }
        });

        btnNuevoClic.setForeground(new java.awt.Color(51, 0, 153));
        btnNuevoClic.setText("Nuevo");
        btnNuevoClic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClicActionPerformed(evt);
            }
        });

        btnModificarClic.setForeground(new java.awt.Color(51, 0, 153));
        btnModificarClic.setText("Modificar");
        btnModificarClic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClicActionPerformed(evt);
            }
        });

        btnBorrarClic.setForeground(new java.awt.Color(51, 0, 153));
        btnBorrarClic.setText("Borrar");
        btnBorrarClic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarClicActionPerformed(evt);
            }
        });

        JTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Apellido", "Nombre", "Perfil"
            }
        ));
        jScrollPane1.setViewportView(JTabla);
        if (JTabla.getColumnModel().getColumnCount() > 0) {
            JTabla.getColumnModel().getColumn(0).setHeaderValue("Apellido");
            JTabla.getColumnModel().getColumn(1).setHeaderValue("Nombre");
            JTabla.getColumnModel().getColumn(2).setHeaderValue("Perfil");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ApellidoTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtApellidoPresionarTecla, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnModificarClic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNuevoClic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnBorrarClic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnVolverClic, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BtnBuscarClic, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ApellidoTitulo)
                    .addComponent(txtApellidoPresionarTecla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnBuscarClic))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevoClic, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnModificarClic, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBorrarClic, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(btnVolverClic)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverClicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverClicActionPerformed
        this.icu.btnVolverClic(evt);
    }//GEN-LAST:event_btnVolverClicActionPerformed

    private void BtnBuscarClicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarClicActionPerformed
        this.icu.btnBuscarClic(evt);
    }//GEN-LAST:event_BtnBuscarClicActionPerformed

    private void btnNuevoClicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClicActionPerformed
        this.icu.btnNuevoClic(evt);
    }//GEN-LAST:event_btnNuevoClicActionPerformed

    private void btnModificarClicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClicActionPerformed
        this.icu.btnModificarClic(evt);
    }//GEN-LAST:event_btnModificarClicActionPerformed

    private void btnBorrarClicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarClicActionPerformed
        this.icu.btnBorrarClic(evt);
    }//GEN-LAST:event_btnBorrarClicActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.icu.ventanaObtenerFoco(evt);
    }//GEN-LAST:event_formWindowGainedFocus

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ApellidoTitulo;
    private javax.swing.JButton BtnBuscarClic;
    private javax.swing.JTable JTabla;
    private javax.swing.JButton btnBorrarClic;
    private javax.swing.JButton btnModificarClic;
    private javax.swing.JButton btnNuevoClic;
    private javax.swing.JButton btnVolverClic;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtApellidoPresionarTecla;
    // End of variables declaration//GEN-END:variables

}
